name: build

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'hotfix/**'
      - 'defect/**'
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: true

    permissions: read-all

    env:
      CI: true

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.18"

      - run: go get -v -t -d ./...

      - run: go build -v .